import React from 'react';
import { Heading, Paragraph } from '@/app/_components/Typography';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Legal | HelloIvy',
  description: 'Legal policies for HelloIvy.ai platform.',
};

type SectionProps = {
  number?: number;
  title: string;
  children: React.ReactNode;
};

const Section: React.FC<SectionProps> = ({ number, title, children }) => (
  <section className="flex flex-col gap-3">
    <Heading level={4} className="font-extrabold text-neutral-900">
      {number !== undefined ? `${number}. ${title}` : title}
    </Heading>
    {children}
  </section>
);

type SubSectionProps = {
  title: string;
  children: React.ReactNode;
};

const SubSection: React.FC<SubSectionProps> = ({ title, children }) => (
  <div className="flex flex-col gap-2">
    <Heading level={5} className="font-bold text-neutral-800">
      {title}
    </Heading>
    {children}
  </div>
);

const BulletList: React.FC<{ items: string[] }> = ({ items }) => (
  <ul className="list-disc space-y-1 pl-6">
    {items.map((item) => (
      <li key={item}>
        <Paragraph size="sm" className="text-neutral-700">
          {item}
        </Paragraph>
      </li>
    ))}
  </ul>
);

const P: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Paragraph size="sm" className="text-neutral-700">
    {children}
  </Paragraph>
);

const LegalPage: React.FC = () => {
  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-10 pb-16">
      {/* Header */}
      <div className="flex flex-col gap-3">
        <Heading level={2} className="font-extrabold text-neutral-900">
          Legal
        </Heading>
        <P>
          This Legal section governs the use of the HelloIvy.ai platform and
          related services. By accessing or using this website or any associated
          services, you agree to the policies outlined below.
        </P>
        <P>
          These policies are designed to ensure transparency, protect users, and
          clearly define the scope and limitations of the services provided.
        </P>
      </div>

      <hr className="border-neutral-200" />

      {/* 1. Terms of Use */}
      <Section number={1} title="Terms of Use">
        <SubSection title="Acceptance of Terms">
          <P>
            By accessing or using HelloIvy.ai, you confirm that you have read,
            understood, and agree to be bound by these Terms of Use and all
            related policies.
          </P>
          <P>
            If you do not agree with any part of these terms, you must
            discontinue use of the platform immediately.
          </P>
          <P>
            If the user is under the age of 18, use of the platform must occur
            under the supervision or authorization of a parent, guardian, school,
            or educational institution.
          </P>
        </SubSection>

        <hr className="border-neutral-200" />

        <SubSection title="Description of Services">
          <P>
            HelloIvy.ai provides an AI-enabled Career & Degree Selection platform
            designed to help students explore potential career domains based on
            responses to structured assessments.
          </P>
          <P>The platform may provide:</P>
          <BulletList
            items={[
              'Career domain recommendations',
              'Lists of potential career pathways',
              'Analytical insights based on assessment responses',
              'Educational guidance resources',
            ]}
          />
          <P>
            The platform is intended solely as an informational and educational
            tool and does not constitute professional, psychological, financial,
            or career counseling advice.
          </P>
          <P>
            All outputs generated by the platform are recommendations and
            exploratory insights, not guarantees of future academic or career
            outcomes.
          </P>
        </SubSection>

        <hr className="border-neutral-200" />

        <SubSection title="Eligibility">
          <P>Users must:</P>
          <BulletList
            items={[
              'Be at least 13 years old, or',
              'Use the platform through an authorized school, parent, or guardian.',
            ]}
          />
          <P>
            Schools and institutions providing access to students confirm that
            they have obtained the necessary parental permissions required under
            applicable laws.
          </P>
        </SubSection>

        <hr className="border-neutral-200" />

        <SubSection title="User Responsibilities">
          <P>Users agree that they will:</P>
          <BulletList
            items={[
              'Provide accurate and truthful information when completing assessments',
              'Use the platform only for lawful educational purposes',
              'Not attempt to reverse engineer, copy, scrape, or exploit the platform',
              'Not misuse or manipulate the assessment system',
            ]}
          />
          <P>
            Any violation may result in suspension or termination of access.
          </P>
        </SubSection>
      </Section>

      {/* 2. Educational Disclaimer */}
      <Section number={2} title="Educational Disclaimer">
        <P>
          HelloIvy.ai provides career exploration insights based on algorithmic
          analysis of user inputs.
        </P>
        <P>The platform:</P>
        <BulletList
          items={[
            'Does not guarantee career success',
            'Does not guarantee admission into any academic program',
            'Does not replace professional counseling',
            'Does not diagnose psychological traits or abilities',
          ]}
        />
        <P>
          Career recommendations are probabilistic suggestions based on patterns
          and data models, not definitive assessments.
        </P>
        <P>
          Students, parents, and schools should use the results as one input
          among many when making academic or career decisions.
        </P>
      </Section>

      {/* 3. AI and Algorithmic Transparency */}
      <Section number={3} title="AI and Algorithmic Transparency">
        <P>
          HelloIvy.ai utilizes artificial intelligence and machine learning
          models trained on historical educational guidance insights and
          structured datasets.
        </P>
        <P>While we continuously improve model accuracy:</P>
        <BulletList
          items={[
            'AI outputs may evolve over time',
            'Results may vary depending on user inputs',
            'No algorithm can fully predict future career success',
          ]}
        />
        <P>
          Users acknowledge that AI systems may occasionally produce imperfect or
          incomplete outputs, and HelloIvy.ai shall not be liable for decisions
          made based on these outputs.
        </P>
      </Section>

      {/* 4. Limitation of Liability */}
      <Section number={4} title="Limitation of Liability">
        <P>
          To the maximum extent permitted by applicable law, HelloIvy.ai, its
          founders, employees, affiliates, partners, and licensors shall not be
          liable for any direct, indirect, incidental, consequential, special, or
          punitive damages arising from:
        </P>
        <BulletList
          items={[
            'Use or inability to use the platform',
            'Career or academic decisions made by users',
            'Interpretation of assessment results',
            'Errors, inaccuracies, or omissions in platform outputs',
            'Technical disruptions or service interruptions',
          ]}
        />
        <P>
          Total liability under any circumstance shall not exceed the amount paid
          for access to the service, if any.
        </P>
      </Section>

      {/* 5. Indemnification */}
      <Section number={5} title="Indemnification">
        <P>
          Users agree to indemnify and hold harmless HelloIvy.ai and its
          affiliates from any claims, liabilities, damages, losses, or expenses
          arising from:
        </P>
        <BulletList
          items={[
            'Misuse of the platform',
            'Violation of these terms',
            'False or misleading information submitted by users',
            'Decisions made based on platform outputs',
          ]}
        />
      </Section>

      {/* 6. Intellectual Property */}
      <Section number={6} title="Intellectual Property">
        <P>
          All content on the platform, including but not limited to:
        </P>
        <BulletList
          items={[
            'Assessments',
            'Algorithms',
            'Data models',
            'Reports',
            'Text, graphics, design, and branding',
          ]}
        />
        <P>
          are the intellectual property of HelloIvy.ai and its licensors.
        </P>
        <P>Users may not:</P>
        <BulletList
          items={[
            'Copy',
            'Reproduce',
            'Redistribute',
            'Modify',
            'Reverse engineer',
          ]}
        />
        <P>any part of the platform without prior written consent.</P>
        <P>Unauthorized use may result in legal action.</P>
      </Section>

      {/* 7. Privacy Policy */}
      <Section number={7} title="Privacy Policy">
        <P>
          HelloIvy.ai is committed to protecting user data and privacy.
        </P>
        <P>
          We collect limited personal information required to operate the
          platform, including:
        </P>
        <BulletList
          items={[
            'Name',
            'Email',
            'Assessment responses',
            'Institutional affiliation (if applicable)',
          ]}
        />
        <P>Data is used for:</P>
        <BulletList
          items={[
            'Generating personalized reports',
            'Improving assessment accuracy',
            'Platform analytics',
          ]}
        />
        <P>We do not sell personal data to third parties.</P>
        <P>
          Users may request data access, correction, or deletion in accordance
          with applicable data protection laws including GDPR, COPPA, and other
          relevant regulations.
        </P>
      </Section>

      {/* 8. Data Security */}
      <Section number={8} title="Data Security">
        <P>
          We implement commercially reasonable technical and organizational
          safeguards to protect data.
        </P>
        <P>
          However, no internet-based system can guarantee absolute security.
        </P>
        <P>
          Users acknowledge that data transmission occurs at their own risk.
        </P>
      </Section>

      {/* 9. Third-Party Services */}
      <Section number={9} title="Third-Party Services">
        <P>
          The platform may integrate or link to third-party tools, websites, or
          educational resources.
        </P>
        <P>
          HelloIvy.ai does not control these services and is not responsible for:
        </P>
        <BulletList
          items={[
            'Their content',
            'Their privacy practices',
            'Their availability',
          ]}
        />
        <P>Users interact with such services at their own discretion.</P>
      </Section>

      {/* 10. Service Availability */}
      <Section number={10} title="Service Availability">
        <P>
          We strive to maintain continuous platform availability but do not
          guarantee uninterrupted service.
        </P>
        <P>HelloIvy.ai may:</P>
        <BulletList
          items={[
            'Modify features',
            'Update algorithms',
            'Temporarily suspend services for maintenance',
          ]}
        />
        <P>without prior notice.</P>
      </Section>

      {/* 11. Global Compliance */}
      <Section number={11} title="Global Compliance">
        <P>
          HelloIvy.ai operates as a digital educational platform accessible
          worldwide.
        </P>
        <P>
          Users are responsible for ensuring their use of the platform complies
          with local laws and regulations applicable in their jurisdiction.
        </P>
      </Section>

      {/* 12. Termination */}
      <Section number={12} title="Termination">
        <P>
          HelloIvy.ai reserves the right to suspend or terminate user access if:
        </P>
        <BulletList
          items={[
            'Terms are violated',
            'Platform misuse is detected',
            'Fraudulent activity occurs',
          ]}
        />
        <P>Termination may occur without prior notice.</P>
      </Section>

      {/* 13. Governing Law */}
      <Section number={13} title="Governing Law">
        <P>
          These terms shall be governed by and interpreted in accordance with the
          laws of the jurisdiction in which HelloIvy.ai is incorporated.
        </P>
        <P>
          Any disputes arising from use of the platform shall be subject to the
          exclusive jurisdiction of the competent courts of that jurisdiction.
        </P>
      </Section>

      {/* 14. Changes to Legal Policies */}
      <Section number={14} title="Changes to Legal Policies">
        <P>
          HelloIvy.ai may update these policies periodically to reflect legal,
          operational, or technological changes.
        </P>
        <P>Users are encouraged to review this page regularly.</P>
        <P>
          Continued use of the platform after updates constitutes acceptance of
          the revised policies.
        </P>
      </Section>
    </div>
  );
};

export default LegalPage;
