import { COUNTRY_NAMES } from './countryCodes';

export const COUNTRY_OPTIONS = COUNTRY_NAMES;

export const STATE_OPTIONS = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Bangalore',
  'Delaware',
  'District of Columbia',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Calgary',
  'Chandigarh',
  'Charlotte',
  'Illinois',
  'Indiana',
  'Coimbatore',
  'Dallas',
  'Delhi',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Doha',
  'Dubai',
  'Edmonton',
  'Louisiana',
  'Maine',
  'Gurgaon',
  'Maryland',
  'Halifax',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'Kochi',
  'Kuwait City',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'Lahore',
  'Las Vegas',
  'Leeds',
  'Lille',
  'Lodz',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Lucknow',
  'Pennsylvania',
  'Puerto Rico',
  'Manama',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Mecca',
  'Minneapolis',
  'Mississauga',
  'Tennessee',
  'Montreal',
  'Texas',
  'New Delhi',
  'Noida',
  'Utah',
  'Ottawa',
  'Pittsburgh',
  'Pune',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Guam',
  'Riyadh',
  'US Virgin Islands',
  'San Antonio',
  'San Diego',
  'San Francisco',
  'San Jose',
  'San Juan',
  'San Jose',
  'San Juan',
  'San Jose',
  'San Juan',
  // Canada
  'Sanaa',
  'Saskatoon',
  'Sharjah',
  'St Louis',
  'St Petersburg',
  'Surat',
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'Ontario',
  'Prince Edward Island',
  'Vancouver',
  'Quebec',
  'Saskatchewan',
  'Northwest Territories',
  'Nunavut',
  'Yukon',
  // India
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
  // Australia
  'Australian Capital Territory',
  'New South Wales',
  'Northern Territory',
  'Queensland',
  'South Australia',
  'Tasmania',
  'Victoria',
  'Western Australia',
  // United Kingdom
  'England',
  'Northern Ireland',
  'Scotland',
  'Wales',
];

export const CITY_OPTIONS = [
  'Abu Dhabi',
  'Abuja',
  'Accra',
  'Addis Ababa',
  'Ahmedabad',
  'Alexandria',
  'Amman',
  'Amsterdam',
  'Ankara',
  'Antwerp',
  'Athens',
  'Atlanta',
  'Auckland',
  'Austin',
  'Bangalore',
  'Bangkok',
  'Barcelona',
  'Beijing',
  'Beirut',
  'Belgrade',
  'Belo Horizonte',
  'Berlin',
  'Bogota',
  'Bologna',
  'Bordeaux',
  'Boston',
  'Brasilia',
  'Brisbane',
  'Brussels',
  'Bucharest',
  'Budapest',
  'Buenos Aires',
  'Busan',
  'Cairo',
  'Calgary',
  'Canberra',
  'Cape Town',
  'Caracas',
  'Casablanca',
  'Chandigarh',
  'Chennai',
  'Chicago',
  'Chongqing',
  'Charlotte',
  'Coimbatore',
  'Cologne',
  'Columbus',
  'Copenhagen',
  'Curitiba',
  'Dallas',
  'Dammam',
  'Dar es Salaam',
  'Delhi',
  'Denver',
  'Dhaka',
  'Doha',
  'Dubai',
  'Dublin',
  'Durban',
  'Edinburgh',
  'Edmonton',
  'Florence',
  'Frankfurt',
  'Fukuoka',
  'Geneva',
  'Glasgow',
  'Guadalajara',
  'Guangzhou',
  'Gurgaon',
  'Halifax',
  'Hamburg',
  'Hangzhou',
  'Hanoi',
  'Harare',
  'Helsinki',
  'Hobart',
  'Ho Chi Minh City',
  'Hong Kong',
  'Houston',
  'Hyderabad',
  'Islamabad',
  'Istanbul',
  'Izmir',
  'Jaipur',
  'Jakarta',
  'Jeddah',
  'Johannesburg',
  'Kansas City',
  'Karachi',
  'Kathmandu',
  'Kigali',
  'Kingston',
  'Kochi',
  'Kolkata',
  'Kuala Lumpur',
  'Kuwait City',
  'Kunming',
  'Kyiv',
  'Lagos',
  'Lahore',
  'Las Vegas',
  'Leeds',
  'Lille',
  'Lima',
  'Lisbon',
  'Lodz',
  'London',
  'Los Angeles',
  'Lucknow',
  'Luxembourg City',
  'Lusaka',
  'Lyon',
  'Madison',
  'Madrid',
  'Manama',
  'Managua',
  'Manila',
  'Marseille',
  'Medellin',
  'Mecca',
  'Melbourne',
  'Mexico City',
  'Miami',
  'Milan',
  'Minneapolis',
  'Mississauga',
  'Monterrey',
  'Montreal',
  'Moscow',
  'Mumbai',
  'Munich',
  'Muscat',
  'Nairobi',
  'Nanjing',
  'Naples',
  'Nashville',
  'New Delhi',
  'New York',
  'Nice',
  'Noida',
  'Orlando',
  'Osaka',
  'Oslo',
  'Ottawa',
  'Paris',
  'Perth',
  'Philadelphia',
  'Phoenix',
  'Pittsburgh',
  'Portland',
  'Porto',
  'Prague',
  'Pretoria',
  'Pune',
  'Quebec City',
  'Qingdao',
  'Quito',
  'Rabat',
  'Recife',
  'Reykjavik',
  'Riyadh',
  'Rome',
  'Rotterdam',
  'Sacramento',
  'Salvador',
  'San Antonio',
  'San Diego',
  'San Francisco',
  'San Jose',
  'San Juan',
  'Sanaa',
  'Santiago',
  'Sao Paulo',
  'Saskatoon',
  'Seattle',
  'Seoul',
  'Sendai',
  'Shanghai',
  'Sharjah',
  'Shenzhen',
  'Singapore',
  'Sofia',
  'St Louis',
  'St Petersburg',
  'Stockholm',
  'Stuttgart',
  'Surat',
  'Sydney',
  'Taipei',
  'Tallinn',
  'Tangier',
  'Tampa',
  'Tehran',
  'Tel Aviv',
  'The Hague',
  'Tokyo',
  'Toronto',
  'Turin',
  'Valencia',
  'Valparaiso',
  'Vancouver',
  'Venice',
  'Victoria',
  'Vienna',
  'Vilnius',
  'Warsaw',
  'Washington',
  'Wellington',
  'Winnipeg',
  'Wroclaw',
  'Yokohama',
  'Zagreb',
  'Zanzibar',
  'Zurich',
];
