import { COUNTRY_NAMES } from '@/app/_constants/countryCodes';

export const COUNTRY_OPTIONS = COUNTRY_NAMES;

// US States
const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
  'Guam',
  'US Virgin Islands',
];

// Canadian Provinces
const CANADA_PROVINCES = [
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Saskatchewan',
  'Northwest Territories',
  'Nunavut',
  'Yukon',
];

// Indian States
const INDIA_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// Australian States
const AUSTRALIA_STATES = [
  'Australian Capital Territory',
  'New South Wales',
  'Northern Territory',
  'Queensland',
  'South Australia',
  'Tasmania',
  'Victoria',
  'Western Australia',
];

// UK Countries
const UK_STATES = [
  'England',
  'Northern Ireland',
  'Scotland',
  'Wales',
];

// Map of countries to their states/provinces
export const STATES_BY_COUNTRY: Record<string, string[]> = {
  'United States': US_STATES,
  'Canada': CANADA_PROVINCES,
  'India': INDIA_STATES,
  'Australia': AUSTRALIA_STATES,
  'UK': UK_STATES,
};

// Legacy export - all states combined (for backward compatibility)
export const STATE_OPTIONS = [
  ...US_STATES,
  ...CANADA_PROVINCES,
  ...INDIA_STATES,
  ...AUSTRALIA_STATES,
  ...UK_STATES,
];

export const CITY_OPTIONS = [
  'Abu Dhabi',
  'Abuja',
  'Accra',
  'Addis Ababa',
  'Ahmedabad',
  'Alexandria',
  'Amman',
  'Amsterdam',
  'Ankara',
  'Antwerp',
  'Athens',
  'Atlanta',
  'Auckland',
  'Austin',
  'Bangalore',
  'Bangkok',
  'Barcelona',
  'Beijing',
  'Beirut',
  'Belgrade',
  'Belo Horizonte',
  'Berlin',
  'Bogota',
  'Bologna',
  'Bordeaux',
  'Boston',
  'Brasilia',
  'Brisbane',
  'Brussels',
  'Bucharest',
  'Budapest',
  'Buenos Aires',
  'Busan',
  'Cairo',
  'Calgary',
  'Canberra',
  'Cape Town',
  'Caracas',
  'Casablanca',
  'Chandigarh',
  'Chennai',
  'Chicago',
  'Chongqing',
  'Charlotte',
  'Coimbatore',
  'Cologne',
  'Columbus',
  'Copenhagen',
  'Curitiba',
  'Dallas',
  'Dammam',
  'Dar es Salaam',
  'Delhi',
  'Denver',
  'Dhaka',
  'Doha',
  'Dubai',
  'Dublin',
  'Durban',
  'Edinburgh',
  'Edmonton',
  'Florence',
  'Frankfurt',
  'Fukuoka',
  'Geneva',
  'Glasgow',
  'Guadalajara',
  'Guangzhou',
  'Gurgaon',
  'Halifax',
  'Hamburg',
  'Hangzhou',
  'Hanoi',
  'Harare',
  'Helsinki',
  'Hobart',
  'Ho Chi Minh City',
  'Hong Kong',
  'Houston',
  'Hyderabad',
  'Islamabad',
  'Istanbul',
  'Izmir',
  'Jaipur',
  'Jakarta',
  'Jeddah',
  'Johannesburg',
  'Kansas City',
  'Karachi',
  'Kathmandu',
  'Kigali',
  'Kingston',
  'Kochi',
  'Kolkata',
  'Kuala Lumpur',
  'Kuwait City',
  'Kunming',
  'Kyiv',
  'Lagos',
  'Lahore',
  'Las Vegas',
  'Leeds',
  'Lille',
  'Lima',
  'Lisbon',
  'Lodz',
  'London',
  'Los Angeles',
  'Lucknow',
  'Luxembourg City',
  'Lusaka',
  'Lyon',
  'Madison',
  'Madrid',
  'Manama',
  'Managua',
  'Manila',
  'Marseille',
  'Medellin',
  'Mecca',
  'Melbourne',
  'Mexico City',
  'Miami',
  'Milan',
  'Minneapolis',
  'Mississauga',
  'Monterrey',
  'Montreal',
  'Moscow',
  'Mumbai',
  'Munich',
  'Muscat',
  'Nairobi',
  'Nanjing',
  'Naples',
  'Nashville',
  'New Delhi',
  'New York',
  'Nice',
  'Noida',
  'Orlando',
  'Osaka',
  'Oslo',
  'Ottawa',
  'Paris',
  'Perth',
  'Philadelphia',
  'Phoenix',
  'Pittsburgh',
  'Portland',
  'Porto',
  'Prague',
  'Pretoria',
  'Pune',
  'Quebec City',
  'Qingdao',
  'Quito',
  'Rabat',
  'Recife',
  'Reykjavik',
  'Riyadh',
  'Rome',
  'Rotterdam',
  'Sacramento',
  'Salvador',
  'San Antonio',
  'San Diego',
  'San Francisco',
  'San Jose',
  'San Juan',
  'Sanaa',
  'Santiago',
  'Sao Paulo',
  'Saskatoon',
  'Seattle',
  'Seoul',
  'Sendai',
  'Shanghai',
  'Sharjah',
  'Shenzhen',
  'Singapore',
  'Sofia',
  'St Louis',
  'St Petersburg',
  'Stockholm',
  'Stuttgart',
  'Surat',
  'Sydney',
  'Taipei',
  'Tallinn',
  'Tangier',
  'Tampa',
  'Tehran',
  'Tel Aviv',
  'The Hague',
  'Tokyo',
  'Toronto',
  'Turin',
  'Valencia',
  'Valparaiso',
  'Vancouver',
  'Venice',
  'Victoria',
  'Vienna',
  'Vilnius',
  'Warsaw',
  'Washington',
  'Wellington',
  'Winnipeg',
  'Wroclaw',
  'Yokohama',
  'Zagreb',
  'Zanzibar',
  'Zurich',
];
