import React from 'react';
import type { JSX } from 'react';
import clsx from 'clsx';

type Variant = 'web' | 'product';
type HeadingLevel = 1 | 2 | 3 | 4 | 5 | 6;
type ParaSize = 'lg' | 'md' | 'sm' | 'xs';
type LabelSize = 'lg' | 'md' | 'sm' | 'xs';
type LabelType = 'label' | 'overline' | 'underline';

/*
DONOT DELETE THIS COMMENT, ITS A HACK TO MAKE SURE THE FOLLOWING CLASSES ARE GENERATED BY tailwindcss
All possible classes for headings, paragraphs, and labels
text-display-sm text-display-lg
text-product-h1 text-product-h2 text-product-h3 text-product-h4 text-product-h5 text-product-h6
text-web-h1 text-web-h2 text-web-h3 text-web-h4 text-web-h5 text-web-h6
text-para-lg text-para-md text-para-sm text-para-xs
text-label-lg text-label-md text-label-sm text-label-xs
text-label-overline-lg text-label-overline-md text-label-overline-sm text-label-overline-xs
text-label-underline-lg text-label-underline-md text-label-underline-sm text-label-underline-xs
leading-product-h1 leading-product-h2 leading-product-h3 leading-product-h4 leading-product-h5 leading-product-h6
leading-web-h1 leading-web-h2 leading-web-h3 leading-web-h4 leading-web-h5 leading-web-h6
leading-para-lg leading-para-md leading-para-sm leading-para-xs
leading-label-lg leading-label-md leading-label-sm leading-label-xs
leading-label-overline-lg leading-label-overline-md leading-label-overline-sm leading-label-overline-xs
leading-label-underline-lg leading-label-underline-md leading-label-underline-sm leading-label-underline-xs
*/

interface DisplayProps {
  size?: 'sm' | 'lg';
  children: React.ReactNode;
  className?: string;
}

export const Display: React.FC<DisplayProps> = ({
  size = 'lg',
  children,
  className = '',
}) => {
  const textClass = `text-display-${size}`;
  const leadingClass = `leading-display-${size}`;

  return (
    <div
      className={clsx(
        `font-darker-grotesque`,
        `text-neutral-900`,
        textClass,
        leadingClass,
        'tracking-tight',
        className
      )}
    >
      {children}
    </div>
  );
};

interface HeadingProps {
  level?: HeadingLevel;
  variant?: Variant;
  children: React.ReactNode;
  className?: string;
}

export const Heading: React.FC<HeadingProps> = ({
  level = 1,
  variant = 'product',
  children,
  className = '',
}) => {
  const Tag = `h${level}` as keyof JSX.IntrinsicElements;
  const textClass = `text-${variant}-h${level}`;
  const leadingClass = `leading-${variant}-h${level}`;

  return (
    <Tag
      className={clsx(
        `font-darker-grotesque`,
        `text-neutral-900`,
        textClass,
        leadingClass,
        'tracking-tight',
        className
      )}
    >
      {children}
    </Tag>
  );
};

interface ParagraphProps {
  size?: ParaSize;
  children: React.ReactNode;
  className?: string;
}

export const Paragraph: React.FC<ParagraphProps> = ({
  size = 'md',
  children,
  className = '',
}) => {
  const textClass = `text-para-${size}`;
  const leadingClass = `leading-para-${size}`;

  return (
    <p
      className={clsx(
        `font-work-sans`,
        textClass,
        leadingClass,
        'tracking-normal',
        `text-neutral-700`,
        className
      )}
    >
      {children}
    </p>
  );
};

interface LabelProps {
  size?: LabelSize;
  type?: LabelType;
  children: React.ReactNode;
  className?: string;
}

export const Label: React.FC<LabelProps> = ({
  size = 'md',
  type = 'label',
  children,
  className = '',
}) => {
  const textClass =
    type === 'label' ? `text-label-${size}` : `text-${type}-${size}`;
  const leadingClass =
    type === 'label' ? `leading-label-${size}` : `leading-${type}-${size}`;

  return (
    <span
      className={clsx(
        `font-work-sans`,
        textClass,
        leadingClass,
        'tracking-normal',
        className
      )}
    >
      {children}
    </span>
  );
};
