export const seniorSecondarySubjects = [
  'Ab Initio Languages',
  'Accountancy',
  'Accounting',
  'Accounts',
  'Additional Mathematics',
  'Advertising & Branding',
  'Agriculture',
  'Algebra I',
  'Algebra II',
  'Anatomy & Physiology',
  'Animal Husbandry',
  'Anthropology',
  'AP Biology',
  'AP Calculus AB',
  'AP Calculus BC',
  'AP Chemistry',
  'AP Comparative Government & Politics',
  'AP Computer Science A',
  'AP Computer Science Principles',
  'AP English Language and Composition',
  'AP English Literature and Composition',
  'AP Environmental Science',
  'AP European History',
  'AP Human Geography',
  'AP Macroeconomics',
  'AP Microeconomics',
  'AP Physics 1',
  'AP Physics 2',
  'AP Physics C: Electricity & Magnetism',
  'AP Physics C: Mechanics',
  'AP Psychology',
  'AP Statistics',
  'AP US Government & Politics',
  'AP US History',
  'AP World History',
  'Applied Mathematics',
  'Arabic',
  'Arabic A Literature',
  'Art',
  'Art & Design',
  'Artificial Intelligence',
  'Assamese',
  'Automobile Technology',
  'Banking',
  'Beauty & Wellness',
  'Bengali',
  'Biology',
  'Biotechnology',
  'Book Keeping',
  'Botany',
  'Business',
  'Business Management',
  'Business Mathematics',
  'Business Studies',
  'Calculus',
  'Chemistry',
  'Child Development',
  'Chinese',
  'Chinese A Literature',
  'Civics',
  'Civil Technology',
  'Classical Civilisation',
  'Classical Languages',
  'Co-ordinated Sciences',
  'Combined Science',
  'Commerce',
  'Commercial Studies',
  "Computer Science / Physical Education / Economics",
  'Computer Applications',
  'Computer Science',
  'Cookery',
  'Cooperation',
  'Craft',
  'Creative Writing',
  'Creativity, Activity, Service (CAS)',
  'Criminology',
  'Dance',
  'Data Entry Operations',
  'Data Science',
  'Design',
  'Design & Creative Arts',
  'Design & Technology',
  'Design Technology',
  'Digital Media',
  'Digital Media & Design',
  'Digital Society',
  'Drama',
  'Drawing',
  'Early Childhood Care & Education',
  'Earth Science',
  'Earth sciences',
  'Economic Applications',
  'Economics',
  'Education & Teaching',
  'Electrical Appliances',
  'Electrical Technology',
  'Electronics',
  'Engineering',
  'Engineering Drawing',
  'Engineering Science',
  'English',
  'English 10',
  'English 11 (American Literature)',
  'English 12 (British Literature / Composition)',
  'English 9',
  'English A Language & Literature',
  'English A Literature',
  'English as a Second Language',
  'English Language',
  'English Language & Literature',
  'English Literature',
  'Enterprise',
  'Entrepreneurship',
  'Environmental & Conservation Studies',
  'Environmental Applications',
  'Environmental Management',
  'Environmental Science',
  'Environmental sciences',
  'Environmental Systems & Societies',
  'Extended Essay (EE)',
  'Fashion & Textiles',
  'Fashion Design',
  'Fashion Designing',
  'Fashion Marketing & Management',
  'Fashion Technology',
  'Film',
  'Film Making',
  'Financial Markets Management',
  'Fine Arts',
  'First Language English',
  'Food & Nutrition',
  'Food Processing',
  'Food Production',
  'Food Science',
  'French',
  'French A Literature',
  'Further Mathematics',
  'Game Development',
  'General Paper',
  'Geography',
  'Geometry',
  'German',
  'German A Literature',
  'Global Perspectives',
  'Global Perspectives & Research',
  'Global Politics',
  'Government / Civics',
  'Graphic Design',
  'Greek',
  'Gujarati',
  'Health',
  'Health Care',
  'Health Science',
  'Health sciences',
  'Health Sciences',
  'Healthcare',
  'Hindi',
  'Hindi A Literature',
  'History',
  'Home Science',
  'Horticulture',
  'Hospitality',
  'Hospitality Management',
  'Individuals and societies',
  'Informatics Practices',
  'Information & Communication Technology',
  'Information & Communication Technology (ICT)',
  'Information Practices',
  'Information Technology',
  'Information Technology Applications',
  'Instrumental Music',
  'Insurance',
  'Interdisciplinary Sciences',
  'International Mathematics',
  'International Relations',
  'Japanese',
  'Journalism',
  'Kannada',
  'Language & Literature in English',
  'Language acquisition',
  'Language and literature',
  'Language B (English, French, Spanish, German, Hindi, etc.)',
  'Latin',
  'Law',
  'Leadership',
  'Legal Studies',
  'Library Science',
  'Life sciences',
  'Literature & Performance',
  'Literature in English',
  'Logic',
  'Malay',
  'Malayalam',
  'Mandarin Chinese',
  'Marathi',
  'Marine Science',
  'Mass Communication',
  'Mass Media',
  'Mass Media & Communication',
  'Mathematics',
  "Mathematics / Informatics Practices / Entrepreneurship",
  'Mathematics Analysis & Approaches HL',
  'Mathematics Analysis & Approaches SL',
  'Mathematics Applications & Interpretation HL',
  'Mathematics Applications & Interpretation SL',
  'Mathematics Basic',
  'Mathematics Standard',
  'Mechanical Drawing',
  'Mechanical Engineering',
  'Mechanical Technology',
  'Media arts',
  'Media Studies',
  'Modern English',
  'Modern Foreign Languages',
  'Moral Science',
  'Multimedia',
  'Music',
  'Music (Indian Vocal)',
  'Music (Western)',
  'Nepali',
  'Nutrition',
  'Odia',
  'Organization of Commerce',
  'Organization of Commerce & Management (OCM)',
  'Painting',
  'Performing Arts',
  'Philosophy',
  'Photography',
  'Physical and health education',
  'Physical Education',
  'Physical Education (PE)',
  'Physical sciences',
  'Physics',
  'Political Science',
  'Portuguese',
  'Pre-Calculus',
  'Psychology',
  "Psychology / Physical Education / Biotechnology",
  'Public Speaking',
  'Punjabi',
  'Pure Mathematics',
  'Regional Language',
  'Regional Languages',
  'Regional languages (depending on school)',
  'Religious Studies',
  'Retail',
  'Retail Management',
  'Robotics',
  'Sanskrit',
  'Science (Physics, Chemistry, Biology combined)',
  'Science & Technology',
  'Sciences',
  'Scripture',
  'Sculpture',
  'Secretarial Practice',
  'Sequential Art / Illustration',
  'Social & Cultural Anthropology',
  'Social Media Strategy',
  'Socially Useful Productive Work (SUPW)',
  'Sociology',
  'Software Development',
  'Sound Design',
  'Spanish',
  'Spanish A Literature',
  'Sport sciences',
  'Sports Management',
  'Sports, Exercise & Health Science',
  'Statistics',
  'Sustainability Management',
  'Tamil',
  'Taxation',
  'Teacher Training',
  'Technical Drawing',
  'Technical Drawing Applications',
  'Technology & Engineering',
  'Telugu',
  'Theater',
  'Theatre',
  'Theatre Studies',
  'Theory of Knowledge (TOK)',
  'Thinking Skills',
  'Tourism',
  'Tourism & Travel',
  'Travel & Tourism',
  'Urdu',
  'US History',
  "User Experience (UX) Design",
  'Visual Arts',
  'Vocational Education',
  'Web Application',
  'Web Designing',
  'World History',
  'World Religions',
  'Yoga',
  'Zoology',
  'Other',
];

export const americanSubjects = [
  'English 9',
  'English 10',
  'English 11 (American Literature)',
  'English 12 (British Literature / Composition)',
  'Creative Writing',
  'Journalism',
  'Public Speaking',
  'Algebra I',
  'Geometry',
  'Algebra II',
  'Pre-Calculus',
  'Calculus',
  'Statistics',
  'Biology',
  'Chemistry',
  'Physics',
  'Environmental Science',
  'Earth Science',
  'Anatomy & Physiology',
  'World History',
  'US History',
  'Government / Civics',
  'Economics',
  'Geography',
  'Psychology',
  'Sociology',
  'Spanish',
  'French',
  'German',
  'Chinese',
  'Latin',
  'Japanese',
  'Visual Arts',
  'Music',
  'Theater',
  'Dance',
  'Photography',
  'Health',
  'Physical Education (PE)',
  'Computer Science',
  'Business Studies',
  'Accounting',
  'Graphic Design',
  'Engineering',
  'Robotics',
  'AP English Language and Composition',
  'AP English Literature and Composition',
  'AP Calculus AB',
  'AP Calculus BC',
  'AP Statistics',
  'AP Computer Science A',
  'AP Computer Science Principles',
  'AP Biology',
  'AP Chemistry',
  'AP Physics 1',
  'AP Physics 2',
  'AP Physics C: Mechanics',
  'AP Physics C: Electricity & Magnetism',
  'AP Environmental Science',
  'AP World History',
  'AP US History',
  'AP European History',
  'AP US Government & Politics',
  'AP Comparative Government & Politics',
  'AP Human Geography',
  'AP Macroeconomics',
  'AP Microeconomics',
  'AP Psychology',
];

export const cambridgeIGCSESubjects = [
  'First Language English',
  'English Literature',
  'English as a Second Language',
  'Mathematics',
  'Additional Mathematics',
  'International Mathematics',
  'Biology',
  'Chemistry',
  'Physics',
  'Combined Science',
  'Co-ordinated Sciences',
  'Environmental Management',
  'History',
  'Geography',
  'Economics',
  'Business Studies',
  'Global Perspectives',
  'Sociology',
  'Religious Studies',
  'Travel & Tourism',
  'French',
  'Spanish',
  'German',
  'Mandarin Chinese',
  'Arabic',
  'Hindi',
  'Urdu',
  'Tamil',
  'Bengali',
  'Malay',
  'Japanese',
  'Latin',
  'Greek',
  'Accounting',
  'Economics',
  'Enterprise',
  'Computer Science',
  'Information & Communication Technology (ICT)',
  'Design & Technology',
  'Engineering',
  'Agriculture',
  'Art & Design',
  'Music',
  'Drama',
  'Physical Education',
  'Media Studies',
  'Food & Nutrition',
  'Fashion & Textiles',
  'Hospitality',
  'Child Development',
];

export const cambridgeALevelSubjects = [
  'Mathematics',
  'Further Mathematics',
  'Statistics',
  'Pure Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Environmental Management',
  'Marine Science',
  'Psychology',
  'Economics',
  'Accounting',
  'Business',
  'Travel & Tourism',
  'History',
  'Geography',
  'Sociology',
  'Global Perspectives & Research',
  'Law',
  'Religious Studies',
  'Literature in English',
  'English Language',
  'English Literature',
  'Language & Literature in English',
  'French',
  'Spanish',
  'German',
  'Arabic',
  'Chinese',
  'Hindi',
  'Urdu',
  'Tamil',
  'Portuguese',
  'Computer Science',
  'Information Technology',
  'Design & Technology',
  'Digital Media & Design',
  'Art & Design',
  'Music',
  'Drama',
  'Media Studies',
  'Thinking Skills',
  'General Paper',
  'Physical Education',
];

export const cbseSubjects = [
  'English Language & Literature',
  'Hindi',
  'Sanskrit',
  'Urdu',
  'French',
  'German',
  'Regional languages (depending on school)',
  'Mathematics Standard',
  'Mathematics Basic',
  'Science (Physics, Chemistry, Biology combined)',
  'History',
  'Geography',
  'Political Science',
  'Economics',
  'Information Technology',
  'Artificial Intelligence',
  'Home Science',
  'Physical Education',
  'Computer Applications',
  'Fine Arts',
  'Physics',
  'Chemistry',
  'Mathematics',
  'English',
  'Computer Science / Physical Education / Economics',
  'Biology',
  'Psychology / Physical Education / Biotechnology',
  'Mathematics / Informatics Practices / Entrepreneurship',
  'Accountancy',
  'Business Studies',
  'Data Science',
  'Web Application',
  'Financial Markets Management',
  'Retail',
  'Tourism',
  'Healthcare',
  'Agriculture',
  'Mass Media',
  'Computer Science',
  'Informatics Practices',
  'Biotechnology',
  'Entrepreneurship',
  'Legal Studies',
];

export const niosSubjects = [
  'English',
  'Hindi',
  'Urdu',
  'Sanskrit',
  'Bengali',
  'Marathi',
  'Telugu',
  'Tamil',
  'Gujarati',
  'Punjabi',
  'Malayalam',
  'Odia',
  'Kannada',
  'Assamese',
  'Nepali',
  'Regional Languages',
  'Mathematics',
  'Business Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Science & Technology',
  'Environmental Science',
  'Geography',
  'History',
  'Political Science',
  'Economics',
  'Psychology',
  'Sociology',
  'Philosophy',
  'Home Science',
  'Data Entry Operations',
  'Computer Science',
  'Information Technology',
  'Web Designing',
  'Accountancy',
  'Business Studies',
  'Commerce',
  'Entrepreneurship',
  'Secretarial Practice',
  'Law',
  'Mass Communication',
  'Library Science',
  'Painting',
  'Drawing',
  'Music',
  'Dance',
  'Theatre',
  'Physical Education',
  'Yoga',
  'Tourism',
  'Hospitality',
  'Agriculture',
  'Early Childhood Care & Education',
  'Teacher Training',
  'Vocational Education',
  'Retail',
  'Health Care',
  'Food Processing',
  'Fashion Design',
  'Beauty & Wellness',
];

export const icseSubjects = [
  'English Language',
  'English Literature',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'History',
  'Civics',
  'Geography',
  'Hindi',
  'Bengali',
  'Gujarati',
  'Marathi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Punjabi',
  'Sanskrit',
  'Urdu',
  'French',
  'German',
  'Spanish',
  'Modern Foreign Languages',
  'Classical Languages',
  'Economics',
  'Economic Applications',
  'Commercial Studies',
  'Commerce',
  'Accounts',
  'Business Studies',
  'Environmental Science',
  'Computer Applications',
  'Computer Science',
  'Information Technology Applications',
  'Technical Drawing Applications',
  'Art',
  'Craft',
  'Fashion Designing',
  'Home Science',
  'Cookery',
  'Hospitality Management',
  'Physical Education',
  'Yoga',
  'Performing Arts',
  'Music (Indian Vocal)',
  'Music (Western)',
  'Instrumental Music',
  'Dance',
  'Drama',
  'Mass Media & Communication',
  'Socially Useful Productive Work (SUPW)',
  'Agriculture',
  'Horticulture',
  'Electrical Appliances',
  'Mechanical Drawing',
  'Engineering Science',
  'Biotechnology',
  'Psychology',
  'Sociology',
  'Legal Studies',
  'Travel & Tourism',
  'Environmental Applications',
  'Modern English',
  'Scripture',
  'Moral Science',
  'Theatre Studies',
];

export const ibSubjects = [
  'English A Language & Literature',
  'English A Literature',
  'Hindi A Literature',
  'French A Literature',
  'Spanish A Literature',
  'German A Literature',
  'Arabic A Literature',
  'Chinese A Literature',
  'Language B (English, French, Spanish, German, Hindi)',
  'Ab Initio Languages',
  'Mathematics Analysis & Approaches SL',
  'Mathematics Analysis & Approaches HL',
  'Mathematics Applications & Interpretation SL',
  'Mathematics Applications & Interpretation HL',
  'Physics',
  'Chemistry',
  'Biology',
  'Environmental Systems & Societies',
  'Computer Science',
  'Design Technology',
  'Sports, Exercise & Health Science',
  'History',
  'Geography',
  'Economics',
  'Business Management',
  'Psychology',
  'Philosophy',
  'Global Politics',
  'Social & Cultural Anthropology',
  'World Religions',
  'Digital Society',
  'Visual Arts',
  'Music',
  'Theatre',
  'Dance',
  'Film',
  'Literature & Performance',
  'Interdisciplinary Sciences',
  'Extended Essay (EE)',
  'Theory of Knowledge (TOK)',
  'Creativity, Activity, Service (CAS)',
];

export const mypSubjects = [
  'Language acquisition',
  'Language and literature',
  'Individuals and societies',
  'Sciences',
  'Mathematics',
  'Physical and health education',
  'Design',
  'Environmental sciences',
  'Life sciences',
  'Physical sciences',
  'Sport sciences',
  'Health sciences',
  'Earth sciences',
  'Dance',
  'Music',
  'Theatre',
  'Media arts',
  'Visual arts',
  'History',
  'Geography',
  'Economics',
  'Global Politics',
  'International Relations',
  'Civics',
  'Philosophy',
  'Business Management',
  'Sociology',
  'Psychology',
  'Anthropology',
];

export const ibcpSubjects = [
  'English A Language & Literature',
  'English A Literature',
  'Hindi A Literature',
  'French A Literature',
  'Spanish A Literature',
  'German A Literature',
  'Arabic A Literature',
  'Chinese A Literature',
  'Language B (English, French, Spanish, German, Hindi, etc.)',
  'Ab Initio Languages',
  'Mathematics Analysis & Approaches SL',
  'Mathematics Analysis & Approaches HL',
  'Mathematics Applications & Interpretation SL',
  'Mathematics Applications & Interpretation HL',
  'Physics',
  'Chemistry',
  'Biology',
  'Environmental Systems & Societies',
  'Computer Science',
  'Design Technology',
  'Sports, Exercise & Health Science',
  'History',
  'Geography',
  'Economics',
  'Business Management',
  'Psychology',
  'Philosophy',
  'Global Politics',
  'Social & Cultural Anthropology',
  'World Religions',
  'Digital Society',
  'Visual Arts',
  'Music',
  'Theatre',
  'Dance',
  'Film',
  'Literature & Performance',
  'Interdisciplinary Sciences',
  'Extended Essay (EE)',
  'Theory of Knowledge (TOK)',
  'Creativity, Activity, Service (CAS)',
  'Business Management',
  'Entrepreneurship',
  'Leadership',
  'Sustainability Management',
  'Artificial Intelligence',
  'Software Development',
  'Engineering',
  'Technology & Engineering',
  'Digital Media',
  'Film Making',
  'Photography',
  'Graphic Design',
  'Advertising & Branding',
  'Game Development',
  'User Experience (UX) Design',
  'Fashion Marketing & Management',
  'Social Media Strategy',
  'Sound Design',
  'Sequential Art / Illustration',
  'Design & Creative Arts',
  'Hospitality Management',
  'Tourism & Travel',
  'Sports Management',
  'Environmental & Conservation Studies',
  'Health Sciences',
  'Criminology',
  'Education & Teaching',
  'Performing Arts',
  'Art & Design',
];

export const hscSubjects = [
  'English',
  'Hindi',
  'Marathi',
  'Sanskrit',
  'Urdu',
  'French',
  'German',
  'Regional Languages',
  'Mathematics',
  'Applied Mathematics',
  'Statistics',
  'Physics',
  'Chemistry',
  'Biology',
  'Computer Science',
  'Information Technology',
  'Electronics',
  'Environmental Science',
  'Geography',
  'History',
  'Political Science',
  'Economics',
  'Psychology',
  'Sociology',
  'Philosophy',
  'Logic',
  'Accountancy',
  'Book Keeping',
  'Business Studies',
  'Organization of Commerce & Management (OCM)',
  'Secretarial Practice',
  'Banking',
  'Cooperation',
  'Agriculture',
  'Animal Husbandry',
  'Home Science',
  'Food Science',
  'Nutrition',
  'Health Science',
  'Physical Education',
  'Fine Arts',
  'Drawing',
  'Painting',
  'Music',
  'Dance',
  'Drama',
  'Vocational Education',
  'Fashion Technology',
  'Travel & Tourism',
  'Retail Management',
  'Media Studies',
  'Taxation',
  'Entrepreneurship',
  'Engineering Drawing',
  'Mechanical Technology',
  'Electrical Technology',
  'Civil Technology',
  'Automobile Technology',
  'Information & Communication Technology',
  'Data Entry Operations',
];

export const iscSubjects = [
  'English',
  'English Literature',
  'Hindi',
  'Sanskrit',
  'Urdu',
  'Bengali',
  'Tamil',
  'French',
  'German',
  'Spanish',
  'Regional Languages',
  'Mathematics',
  'Applied Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Biotechnology',
  'Computer Science',
  'Information Practices',
  'Electronics',
  'Environmental Science',
  'Geography',
  'History',
  'Political Science',
  'Sociology',
  'Psychology',
  'Economics',
  'Commerce',
  'Accounts',
  'Business Studies',
  'Legal Studies',
  'Mass Media & Communication',
  'Home Science',
  'Fashion Designing',
  'Hospitality Management',
  'Travel & Tourism',
  'Art',
  'Painting',
  'Sculpture',
  'Music',
  'Dance',
  'Theatre',
  'Physical Education',
  'Yoga',
  'Philosophy',
  'Statistics',
  'Technical Drawing',
  'Engineering Science',
  'Classical Civilisation',
  'Modern Foreign Languages',
];

export const stateBoardSubjects = [
  'English',
  'Hindi',
  'Regional Language',
  'Marathi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Gujarati',
  'Punjabi',
  'Bengali',
  'Odia',
  'Assamese',
  'Urdu',
  'Sanskrit',
  'French',
  'German',
  'Spanish',
  'Arabic',
  'Mathematics',
  'Applied Mathematics',
  'Statistics',
  'Physics',
  'Chemistry',
  'Biology',
  'Botany',
  'Zoology',
  'Computer Science',
  'Information Technology',
  'Data Science',
  'Artificial Intelligence',
  'Electronics',
  'Environmental Science',
  'History',
  'Geography',
  'Political Science',
  'Civics',
  'Economics',
  'Sociology',
  'Psychology',
  'Philosophy',
  'Logic',
  'Accountancy',
  'Business Studies',
  'Commerce',
  'Organization of Commerce',
  'Secretarial Practice',
  'Banking',
  'Insurance',
  'Agriculture',
  'Home Science',
  'Nutrition',
  'Health Science',
  'Physical Education',
  'Yoga',
  'Art',
  'Drawing',
  'Painting',
  'Music',
  'Dance',
  'Drama',
  'Theatre',
  'Fine Arts',
  'Fashion Designing',
  'Hospitality Management',
  'Travel & Tourism',
  'Mass Media',
  'Journalism',
  'Legal Studies',
  'Entrepreneurship',
  'Retail Management',
  'Taxation',
  'Engineering Drawing',
  'Mechanical Engineering',
  'Electrical Technology',
  'Civil Technology',
  'Automobile Technology',
  'Biotechnology',
  'Food Production',
  'Library Science',
  'Vocational Education',
  'Teacher Training',
  'Beauty & Wellness',
  'Food Processing',
  'Web Designing',
  'Multimedia',
];
